### ISSUE TITLE
Split plugin unrelated code into ghc-tags-core?

### ISSUE THREAD

**Issue by arybczak** [coot/ghc-tags-plugin#24]
I'm working on non-plugin version of this package (https://github.com/arybczak/ghc-tags) since I'd like to have something closer to hasktags and I wonder if it makes sense to put common functionality into separate package so that we don't have to do things twice.

Thanks for putting this package up btw, I've been unhappy with hasktags for some time now, but didn't care enough to figure out GHC API for everything. But since you've done a lot of the heavy lifting by writing code for extracting tags, it gave me motivation to try and fill out the blanks ;)

**Comment by coot** [comment]
Nice, I wanted to do it next :) for various reasons: installing `ghc` plugins is not a smooth experience at the moment, one does not have access to ast parsed with different `DynFlags` (more why this would be useful below).

> I wonder if it makes sense to put common functionality into separate package so that we don't have to do things twice.

Sure.  These modules are non plugin specific and can be lifted to a shared library:

* `Plugin.GhcTags.Generate`
* `Plugin.GhcTags.CTags.Formatter`
* `Plugin.GhcTags.CTags.Parser`
* `Plugin.GhcTags.Etags.Formatter`
* `Plugin.GhcTags.Etags.Parser`
* `Plugih.GhcTags.Tags`

With `ctags` one has more flexibility than with `etags`: e.g. kinds, tag fields, but also order of tags can be tweaked.

For a command line tool I wanted to generate tags for all possible settings of `CPP` flags (or at least for different os-es, so that the code which is is os-specific, is still visible on other platforms).

**Comment by coot** [comment]
Checkout `ghc-tags-core`.
