### ISSUE TITLE
is the ghc-lib dependency really a ghc-lib-parser dependency?

### ISSUE THREAD

**Issue by shayne-fletcher** [coot/ghc-tags-plugin#77]
i see that ghc-tags-plugin directly depends on ghc-lib. i wonder if in fact the dependency is completely satisfied by ghc-lib-parser? (i ask because i am considering there may not be sufficient users of ghc-lib to justify more releases).

**Comment by coot** [comment]
Likely, but also `ghc-lib` and `ghc-lib-parser` are not right targets for any plugin.  I only supported it to integrate with `ghc-tags`, but since there's no easy way to let `ghc-tags` decide which cabal flags it should use when building a dependency (that's a cabal limitation), I decided to fork it instead.  Now there's no good reason to actually use `ghc-lib` (or `ghc-lib-parser`) in `ghc-tags-core` package.
